### PR TITLE
Update to use UptimeRobot APIv2

### PR DESCRIPTION
**Pull request by avondohren**
This PR is to update this gem to support UptimeRobot APIv2. The APIv1 will be retired by 1 Oct 2017. This change includes a commit from @diegoadt that did most of the grunt work to get APIv2 up and running. I worked on updating the readme and a couple of variable name changes to make the change more understandable.

This is my first open source PR, so let me know if there is anything I should clean up or additional information I should provide.

### CODE REVIEW

**Comment by avondohren** [comment]
I see that we missed updating the tests. Working on getting those passing now.

**Comment by avondohren** [comment]
Tests are passing with minimal updates to reflect the changes in APIv2

**Comment by diramos1** [comment]
:clap: :clap: :clap: thanks @avondohren, I reviewed and for me, your PR can be merged.

**Comment by avondohren** [comment]
Uptime Robot did change the actual endpoints and parameter names, so apps that update will need to make those changes in their own code as well. Not sure how exactly to talk about that in the PR / in the README.md (maybe?).

**Comment by diramos1** [comment]
But by the PR, the gem is in another minor version, right? So, if apps uses this gem they won't update to this specific version without manual intervention.

**Comment by diramos1** [comment]
@winebarrel any suggestion?

**Comment by willdurand** [comment]
Also tested it in production, works very well 👍

**Comment by winebarrel** [comment]
Sorry for the late reply.

@avondohren Thanks you for your PR! 👍 

I will write the following note in the README.

```
If you want to use V1 API, please specify as follows.

> gem 'uptimerobot', '~> 0.1.6`
```

**Comment by winebarrel** [comment]
v0.2.0. has been released. 😃

**Pull request merged**
